# Generated by Django 2.1.5 on 2019-03-01 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('unique_key', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('story_headline', models.CharField(max_length=64)),
                ('story_details', models.CharField(max_length=512)),
                ('story_category', models.CharField(max_length=64)),
                ('story_region', models.CharField(max_length=64)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.Author')),
            ],
        ),
    ]
