# Generated by Django 2.1.5 on 2019-03-01 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0002_auto_20190301_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='story_details',
            field=models.CharField(max_length=512, unique=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='story_headline',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='story',
            unique_together=set(),
        ),
    ]
