# Generated by Django 2.1.5 on 2019-03-03 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0003_auto_20190301_1607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='created_time',
            new_name='story_date',
        ),
    ]
